name: CI

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: "18.x"
    - run: npm ci
    - run: make check-rules-are-up-to-date
    - run: make check-all-rules-are-considered
    - run: npm run format
    - run: npm test
